name: second_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  internet_connection_checker: ^2.0.0
  http: ^1.2.2
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.2.3
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/